* Steps for Case Study:

* Data Cleaning:
    *    Import Necessary Libraries
    *    Load the dataset
    *    Data Understanding {important}
    *    Problem Statement Understanding
    *    Missing Value Check
    *    Segmentation


# Loading Data & Data Dictionary

#### Data Loading

In [43]:
# import all the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [64]:
# Read the Csv file
df = pd.read_csv('loan.csv')
# Fetch the top 5 rows
df.head()

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  1077501    1296599       5000         5000           4975.0   36 months   
1  1077430    1314167       2500         2500           2500.0   60 months   
2  1077175    1313524       2400         2400           2400.0   36 months   
3  1076863    1277178      10000        10000          10000.0   36 months   
4  1075358    1311748       3000         3000           3000.0   60 months   

  int_rate  installment grade sub_grade  ... num_tl_90g_dpd_24m  \
0   10.65%       162.87     B        B2  ...                NaN   
1   15.27%        59.83     C        C4  ...                NaN   
2   15.96%        84.33     C        C5  ...                NaN   
3   13.49%       339.31     C        C1  ...                NaN   
4   12.69%        67.79     B        B5  ...                NaN   

  num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75 pub_rec_bankruptcies  \
0                NaN            NaN               NaN                  0.0   
1                NaN            NaN               NaN                  0.0   
2                NaN            NaN               NaN                  0.0   
3                NaN            NaN               NaN                  0.0   
4                NaN            NaN               NaN                  0.0   

  tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit  \
0       0.0             NaN               NaN            NaN   
1       0.0             NaN               NaN            NaN   
2       0.0             NaN               NaN            NaN   
3       0.0             NaN               NaN            NaN   
4       0.0             NaN               NaN            NaN   

  total_il_high_credit_limit  
0                        NaN  
1                        NaN  
2                        NaN  
3                        NaN  
4                        NaN  

[5 rows x 111 columns]

#### Loading Data Dictionary 

In [65]:
dictionary = pd.read_excel('./Data_Dictionary.xlsx')
dictionary

LoanStatNew                                        Description
0           acc_now_delinq  The number of accounts on which the borrower i...
1     acc_open_past_24mths         Number of trades opened in past 24 months.
2               addr_state  The state provided by the borrower in the loan...
3                 all_util              Balance to credit limit on all trades
4               annual_inc  The self-reported annual income provided by th...
..                     ...                                                ...
112    verification_status  Indicates if income was verified by LC, not ve...
113  verified_status_joint  Indicates if the co-borrowers' joint income wa...
114               zip_code  The first 3 numbers of the zip code provided b...
115                    NaN                                                NaN
116                    NaN  * Employer Title replaces Employer Name for al...

[117 rows x 2 columns]

## Data Cleaning

#### Columns Review

In [66]:
df.shape

(39717, 111)

This Dataset contains total 111 columns and 39,717 rows

In [67]:
# Problem Statement: Analyse the data to find the Variables/Factors affecting leading to loan defaulters.
df.info(verbose='true')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 111 columns):
 #    Column                          Dtype  
---   ------                          -----  
 0    id                              int64  
 1    member_id                       int64  
 2    loan_amnt                       int64  
 3    funded_amnt                     int64  
 4    funded_amnt_inv                 float64
 5    term                            object 
 6    int_rate                        object 
 7    installment                     float64
 8    grade                           object 
 9    sub_grade                       object 
 10   emp_title                       object 
 11   emp_length                      object 
 12   home_ownership                  object 
 13   annual_inc                      float64
 14   verification_status             object 
 15   issue_d                         object 
 16   loan_status                     object 
 17   pymnt_plan

#### Dropping Rows

In [68]:
# Dropping all the rows where loan status is Current
# These loans will not contribute into in the decisions (Pass or fail) as they are still in progress
print("Number of rows where loan status is Current",len(df[df['loan_status'] == 'Current']))
df = df[df['loan_status'] != "Current"]

Number of rows where loan status is Current 1140


In [69]:
# Dropping all rows which are duplicate
df.duplicated().sum()

#There are no duplicate rows

0

In [70]:
print("Final shape of the data after dropping rows", df.shape)

Final shape of the data after dropping rows (38577, 111)


#### Dropping Columns

**Missing Value Check**

In [71]:
# identify the columns which have all NAs
na_col_list = df.columns[df.isna().all()]
print("Columns with 100% missing Value:", list(na_col_list))
print("Total number of columns with 100% missing Value:", len(na_col_list))

# removing the columns with 100% missing data
df.drop(na_col_list, axis=1, inplace=True)

Columns with 100% missing Value: ['next_pymnt_d', 'mths_since_last_major_derog', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'tot_hi_cred_lim', 'total_bal_e

In [72]:
# Identifying all the columns which contains all unique values
unique_cols = df.columns[df.nunique() == len(df)]
print("Columns with 100% unique Values:", list(unique_cols))

# removing the columns with 100% unique values
df.drop(unique_cols, axis=1, inplace=True)

Columns with 100% unique Values: ['id', 'member_id', 'url']


In [73]:
# Removing the description and title columns as they don't contribute into the analysis
df.drop(['emp_title', 'desc', 'title'], axis=1, inplace=True)

In [89]:
# Identifying all the columns which contains constant value
constant_cols = df.columns[df.nunique() == 1]
print("Columns with constant Values:", list(constant_cols))

# removing the columns with constant value
df.drop(constant_cols, axis=1, inplace=True)

Columns with constant Values: ['pymnt_plan', 'initial_list_status', 'out_prncp', 'out_prncp_inv', 'collections_12_mths_ex_med', 'policy_code', 'application_type', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt', 'tax_liens']


In [94]:
# identify the columns which have more than 60% missing values
na_col_list = df.columns[df.isna().mean() >= 0.60]
print("Columns with more than 60% missing Value:", list(na_col_list))

# removing the columns with more than 60% missing data
df.drop(na_col_list, axis=1, inplace=True)

Columns with more than 60% missing Value: ['mths_since_last_delinq', 'mths_since_last_record']


In [96]:
print("Final Shape of the Dataset", df.shape)

Final Shape of the Dataset (38577, 37)
